### PR TITLE
Implemented to load CWL from a list

### PR DESCRIPTION
**Pull request by bldevries-escience**
scriptcwl.load_steps can now load CWL files from a list of files/directories and or http urls.

### CODE REVIEW

**Comment by jvdzwaan** [comment]
Could you add a test that checks if it works?

**Comment by bldevries-escience** [comment]
Im on it

**Comment by bldevries-escience** [comment]
I added a test to check if it works. Besides using a list, it also checks if it can read 'https://raw.githubusercontent.com/WhatWorksWhenForWhom/nlppln/develop/cwl/anonymize.cwl'. Is it nice to do it that way?

**Comment by bldevries-escience** [comment]
For some reason Travis-ci crashed on importing the 'https://raw.githubusercontent.com/WhatWorksWhenForWhom/nlppln/develop/cwl/anonymize.cwl'. It worked fine locally on my machine. Any ideas? 
For now I took out the http url in the tests. I will look at it tomorrow.

**Pull request merged**
